---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: hello-world
  labels:
    name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: hello-world
    spec:
      containers:
      - name: hello-world
        image: gcr.io/trusty-drive-219516/r/go-hello-world
        ports:
        - containerPort: 8080
